/**
 * Generate the requirement traceability matrix.
 *
 * Three artifacts state the same contract: the prose declares a rule, the
 * schema or the semantic phase enforces it, and a fixture pins the outcome.
 * Nothing showed those three together, so "is this rule tested" was a question
 * you answered by grepping.
 *
 * Generated rather than maintained, for the reason `catalog.json` is: a matrix
 * someone has to remember to update is a matrix that is wrong.
 *
 * NON-NORMATIVE, like everything under tools/.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join, posix } from 'node:path'
import {
  conformanceLink,
  discoverFamilies,
  type Family,
  familyPaths,
  inRepo,
  isObject,
  type Json,
  REPO_ROOT,
  readJson,
  relativeToRepo,
  repoLink,
  TRACEABILITY_FILE,
} from '../lib/layout.ts'
import { readOutline } from '../lib/outline.ts'

const OUTPUT = inRepo(REPO_ROOT, TRACEABILITY_FILE)
/** The directory the matrix is read from, which every link in it is relative to. */
const OUTPUT_DIR = posix.dirname(TRACEABILITY_FILE)

/** A conformance case citing a requirement. */
interface Citation {
  readonly family: string
  readonly major: string
  /** The case directory, relative to its family version's corpus. */
  readonly path: string
  readonly behaviorId?: string
}

interface Requirement {
  readonly id: string
  readonly family: string
  readonly section: string
  readonly sectionTitle: string
  readonly specPath: string
}

/**
 * A section title as a clause cell shows it: plain text, with no anchor markup.
 *
 * A heading carrying more than one anchor, as
 * `## <a id="type"></a><a id="workload"></a>5. The component's shape`, reaches
 * here with every anchor after the first, and its number, still in the title.
 * The cell links to the section already, so the anchors are noise, and the
 * number is dropped to match the headings with one anchor.
 */
export function clauseTitle(title: string): string {
  return title
    .replace(/<a id="[^"]*"><\/a>/g, '')
    .trim()
    .replace(/^[0-9]+(?:\.[0-9]+)*\.?\s+/, '')
}

function requirementsIn(family: Family): Requirement[] {
  if (!existsSync(family.specPath)) return []
  const outline = readOutline(readFileSync(family.specPath, 'utf8'))
  const titles = new Map(outline.sections.map((section) => [section.id, section.title]))
  return [...outline.requirements].map(([id, section]) => ({
    id,
    family: family.name,
    section,
    sectionTitle: clauseTitle(titles.get(section) ?? ''),
    specPath: familyPaths(family.name, family.major).spec,
  }))
}

/** Requirement ID to the cases citing it, across every family's corpus. */
function citations(repoRoot: string): Map<string, Citation[]> {
  const cited = new Map<string, Citation[]>()
  for (const family of discoverFamilies(repoRoot)) {
    const indexPath = join(family.conformanceDir, 'cases.json')
    if (!existsSync(indexPath)) continue
    const index = readJson(indexPath)
    const cases = isObject(index) && Array.isArray(index.cases) ? index.cases : []

    const behaviorPath = join(family.conformanceDir, 'behavior.json')
    if (existsSync(behaviorPath)) {
      const behavior = readJson(behaviorPath)
      if (Array.isArray(behavior))
        for (const c of behavior) {
          if (!isObject(c) || typeof c.id !== 'string' || !Array.isArray(c.requirements)) continue
          for (const requirement of c.requirements)
            if (typeof requirement === 'string') {
              const citation = {
                family: family.name,
                major: family.major,
                path: 'behavior.json',
                behaviorId: c.id,
              }
              cited.set(requirement, [...(cited.get(requirement) ?? []), citation])
            }
        }
    }
    for (const entry of cases as Json[]) {
      if (!isObject(entry) || typeof entry.path !== 'string') continue
      const metadata = readJson(join(family.conformanceDir, entry.path, 'metadata.json'))
      if (!isObject(metadata) || !Array.isArray(metadata.requirements)) continue
      for (const requirement of metadata.requirements) {
        if (typeof requirement !== 'string') continue
        const citation = { family: family.name, major: family.major, path: entry.path }
        cited.set(requirement, [...(cited.get(requirement) ?? []), citation])
      }
    }
  }
  return cited
}

/**
 * The matrix, one section per family version. `discoverFamilies` puts core
 * first, so the requirements every family shares are read before the ones a
 * family adds.
 */
export function buildMatrix(repoRoot: string = REPO_ROOT): string {
  const cited = citations(repoRoot)
  const lines: string[] = [
    '# Requirement traceability',
    '',
    '**Generated by `task docs` — do not edit.**',
    '',
    'Every requirement this specification gives a stable identifier, the clause',
    'that states it, and the conformance cases that pin it.',
    '',
    'A requirement with no case is not necessarily untested — some are excused in',
    "`tools/src/conformance/conformance.ts`'s `UNPINNED` list, each with a written reason. What",
    'this table makes visible is which rules the corpus actually holds down.',
    '',
  ]

  let total = 0
  let pinned = 0

  for (const family of discoverFamilies(repoRoot)) {
    const requirements = requirementsIn(family)
    if (requirements.length === 0) continue

    lines.push(`## ${family.name}/${family.major}`, '')
    lines.push('| Requirement | Clause | Cases |', '|---|---|---|')

    for (const requirement of requirements) {
      total += 1
      const cases = cited.get(requirement.id) ?? []
      if (cases.length > 0) pinned += 1

      const spec = repoLink(OUTPUT_DIR, requirement.specPath)
      const clause = `[§${requirement.sectionTitle}](${spec}#${requirement.section})`
      const links = cases
        .map(
          (c) =>
            `[\`${c.family}/${c.major}/${c.behaviorId ?? c.path}\`](${c.behaviorId ? repoLink(OUTPUT_DIR, familyPaths(c.family, c.major).conformance + '/' + c.path) : conformanceLink(OUTPUT_DIR, c.family, c.major, c.path)})`,
        )
        .join('<br>')
      lines.push(
        `| [\`${requirement.id}\`](${spec}#${requirement.id}) | ${clause} | ${links || '—'} |`,
      )
    }
    lines.push('')
  }

  lines.push(
    `${pinned} of ${total} requirement(s) are pinned by at least one conformance case.`,
    '',
  )
  return lines.join('\n')
}

function main(): void {
  const matrix = buildMatrix()
  writeFileSync(OUTPUT, matrix, 'utf8')
  console.log(`  ✓ ${relativeToRepo(OUTPUT)}`)
}

if (import.meta.main) main()
