specVersion: v1
kind: COMPONENT
metadata:
  revision: 1
spec:
  workload:
    type: SERVICE
    source:
      type: IMAGE
      ref: nginx:1.29.4-alpine
    endpoints:
      internal:
        containerPort: 8080
        protocol: HTTP
  contract:
    inputs:
      selfUrl:
        schema:
          type: string
        description: URL the application advertises for itself.
        target:
          envVarKey: SELF_URL
    outputs:
      installDefault:
        description: Node-specific default address
        schema:
          type: string
        source:
          type: TEMPLATE
          template: ${{ self.publicUrl.internal }}
